### ISSUE TITLE
Doesn't work with ES6 modules/typescript

### ISSUE THREAD

**Issue by alexkreidler** [kristianmandrup/json-schema-model-builder#2]
Running the example code in the README,  I get these errors:
```
 pnpm ts-node src/build.ts                                         (langchain) 
Error: Cannot find module './build'
Require stack:
- /project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js
- /project/express-autocrud/src/build.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/project/express-autocrud/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .js] (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1089:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js',
    '/project/express-autocrud/src/build.ts'
  ]
}
[14:38:39] alex@alex-brain /project/express-autocrud > pnpm ts-node src/build.ts                                         (langchain) 
Error: Cannot find module './build'
Require stack:
- /project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js
- /project/express-autocrud/src/build.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/project/express-autocrud/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js:6:34)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .js] (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1089:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/express-autocrud/node_modules/.pnpm/json-schema-model-builder@0.2.1/node_modules/json-schema-model-builder/src/index.js',
    '/project/express-autocrud/src/build.ts'
  ]
}
[14:39:18] alex@alex-brain /project/express-autocrud > pnpm ts-node src/build.ts                                         (langchain) 
/project/express-autocrud/src/build.ts:12
const state = createState({ config });
                         ^
TypeError: (0 , json_schema_model_builder_1.createState) is not a function
    at Object.<anonymous> (/project/express-autocrud/src/build.ts:12:26)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module.m._compile (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .ts] (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/project/express-autocrud/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.2.5_typescript@5.1.3/node_modules/ts-node/src/bin.ts:95:10)
```

**Comment by kristianmandrup** [comment]
I guess the project needs to be updated to work with modern JavaScript/Typescript.
